"""first migration

Revision ID: 6567465d0255
Revises: 
Create Date: 2024-12-19 02:26:03.465575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6567465d0255'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('hash_password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='auctora_dev'
    )
    op.create_index(op.f('ix_auctora_dev_users_email'), 'users', ['email'], unique=True, schema='auctora_dev')
    op.create_index(op.f('ix_auctora_dev_users_id'), 'users', ['id'], unique=False, schema='auctora_dev')
    op.create_index(op.f('ix_auctora_dev_users_username'), 'users', ['username'], unique=True, schema='auctora_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auctora_dev_users_username'), table_name='users', schema='auctora_dev')
    op.drop_index(op.f('ix_auctora_dev_users_id'), table_name='users', schema='auctora_dev')
    op.drop_index(op.f('ix_auctora_dev_users_email'), table_name='users', schema='auctora_dev')
    op.drop_table('users', schema='auctora_dev')
    # ### end Alembic commands ###
